version: '3.7'
services:
  redis:
    image: "redis:7.0.11"
    container_name: "redis-hermes-hai"
    environment:
      - REDIS_PASSWORD=xxx
    command: redis-server --appendonly yes --save 900 1 300 10 60 10000 --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "xxxx:xxxx" # xxxx:xxxx for the next one.
    networks:
      - hermes-network

  mariadb:
    image: "mariadb:xx.xx.x"
    container_name: "mariadb-hermes"
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
    ports:
      - "xxxx:xxxx"
    networks:
      - hermes-network

volumes:
  redis_data:
  mariadb_data:

networks:
  hermes-network:
